### ISSUE TITLE
[Request] Global settings for 1366x768 monitor

### ISSUE THREAD

**Issue by linuxmobile** [garado/cozy#1]
Hi, i want to know if there is a way to get this settings working in 1366x768 monitors?

The dashboard is to big and impossible to get working!

**Comment by garado** [comment]
Next on my to do list! I'll be able to get to this within the next few days

**Comment by garado** [comment]
@linuxmobile do you need the other popups resized as well or just the dashboard?

**Comment by linuxmobile** [comment]
> @linuxmobile do you need the other popups resized as well or just the dashboard?

Just dashboard! Other popups r nice!

**Comment by linuxmobile** [comment]
> @linuxmobile do you need the other popups resized as well or just the dashboard?

Was there any progress?

**Comment by linuxmobile** [comment]
We are approaching a year and there is still no support for small monitors :(

**Comment by garado** [comment]
Happy 1 year anniversary of this issue lol. Resolved a reaaally long time ago with the addition of the scale setting in the configuration options

**Comment by linuxmobile** [comment]
> Happy 1 year anniversary of this issue lol. Resolved a reaaally long time ago with the addition of the scale setting in the configuration options

The true King of kings <3 !! I  will try later! Thx u
