### ISSUE TITLE
(NOT A BUG) You Totally Should Check Out Anytype

### ISSUE THREAD

**Issue by Thomashighbaugh** [garado/cozy#7]
First love the setup, looks great and the code is rock solid to go with it. Also love Santa Cruz, spent time with the local homeless kids there the week I walked up Mount Henry and then back down (long story, very Central Coast hippie but I live life as it comes as a religious principle that's not important but something I am aware makes me seem crazy, maybe I am that's fine)

Your organization dashboard is awesome, don't get me wrong, but the program [Anytype](https://download.anytype.io/) as it seems right up your alley in terms of features and functions, which probably has some AUR package but I use NixOS and things are different with packages (I love adding unnecessary complexity to my life what can I say...), has a mobile app so you never have to escape obsessive organization where ever you are and is `almost` in the same color scheme you use. Were I not already settled on using topical and repository-specific Markdown "notebooks" backed up with Git and Dropbox **and** weary of having an all-in-one workspace given the tendency to spend more time documenting my life than living it when I have tried as much, I would move to using it myself. My experimenting with it indicates it is a far better and lighter-weight/more responsive Notion experience with a better way of integrating templates to actually save time and not just sell crap on Gumroad. 

Even if its not your thing, just thought I would shoot the idea your way. Keep up the great work! 

- TLH

**Comment by garado** [comment]
I'm glad you like the dashboard! I checked out Anytype and it does look very very cool. It seems to have everything that I found lacking in Notion. I think I'm too deeply entrenched in my own little ecosystem to switch (I use my own md/Git notes system too) but I will be taking design inspiration from Anytype. Thank you for letting me know about it!
